"""
Class-based forward model for predicting N(z) from an evolving Schechter
luminosity function (e.g. for WAVES-Wide/Deep-style Z-band flux-limited
samples), plus a joint 3-parameter fit of

    z_c(m) = a * (m - m0)^p + c

to the model's OWN predicted redshift distributions, sliced into
apparent-magnitude bins (default 16-22 in steps of 1) -- i.e. the same
fitting machinery used previously on real catalogues, but now fed
synthetic dN/dz curves generated by the physical LF model instead.

Cosmology fixed to match the LF fit: H0=100, Om=0.3, OL=0.7 (h=1),
so no h-scaling conversions are needed anywhere in this pipeline.
"""

import numpy as np
import mpmath
from scipy.optimize import curve_fit
from astropy.cosmology import LambdaCDM
from astropy import units as u
import matplotlib.pyplot as plt


# =====================================================================
# 1. Forward model: evolving Schechter LF -> predicted dN/dz
# =====================================================================
class SchechterNzModel:
    """
    Forward-models dN/dz for a flux-limited sample from an evolving
    Schechter luminosity function.

    Provides both the cumulative flux-limited prediction (all galaxies
    brighter than a single apparent-magnitude limit) and the sliced
    prediction (galaxies within an apparent-magnitude range), the
    latter being what's needed to build synthetic n(z | m) histograms
    analogous to real catalogue data.
    """

    def __init__(
        self,
        H0=100.0, Om0=0.3, Ode0=0.7,
        Mstar0=-21.814943193345457,
        alpha=-1.3166859304357672,
        phistar0=0.004938332759020672,   # Mpc^-3 mag^-1 (h=1)
        P=1.625,       # density evolution
        Q=-0.07875,    # luminosity evolution
        Mmin=-24.25, Mmax=-13.5,          # valid abs-mag range of the LF fit
        zfit_max=0.5,                      # valid redshift range of the LF fit
        kcorr=None,
    ):
        self.cosmo = LambdaCDM(H0=H0, Om0=Om0, Ode0=Ode0)
        self.Mstar0 = Mstar0
        self.alpha = alpha
        self.phistar0 = phistar0
        self.P = P
        self.Q = Q
        self.Mmin = Mmin
        self.Mmax = Mmax
        self.zfit_max = zfit_max
        # placeholder pure bandpass-compression K-correction by default;
        # swap in a real VISTA-native K(z) polynomial via the kcorr= kwarg
        self.kcorr = kcorr if kcorr is not None else self._default_kcorr

    @staticmethod
    def _default_kcorr(z):
        return 2.5 * np.log10(1.0 + z)

    # -----------------------------------------------------------
    def schechter_params(self, z):
        """Evolve M*, phi* to redshift z. alpha held fixed."""
        Mstar = self.Mstar0 - self.Q * z
        phistar = self.phistar0 * 10 ** (0.4 * self.P * z)
        return Mstar, phistar, self.alpha

    def n_brighter_than(self, Mlim, z):
        """
        Number density (Mpc^-3) of galaxies with M < Mlim at redshift z,
        via the unnormalized upper incomplete gamma function (mpmath
        supports the negative, non-integer order alpha+1 that scipy
        cannot).
        """
        Mstar, phistar, a = self.schechter_params(z)
        x = 10 ** (0.4 * (Mstar - Mlim))
        if x <= 0:
            x = 1e-8  # avoid divergence as x -> 0 for alpha+1 <= 0
        val = mpmath.gammainc(a + 1, x, mpmath.inf)
        return phistar * float(val)

    # -----------------------------------------------------------
    def distance_modulus(self, z):
        d_L = self.cosmo.luminosity_distance(z).to(u.Mpc).value
        return 5 * np.log10(d_L) + 25

    def Mlim_of_z(self, z, Zlim):
        """M_lim(z) = Zlim - DM(z) - K(z). Q-evolution is NOT re-applied
        here since it's already folded into schechter_params via M*(z)."""
        return Zlim - self.distance_modulus(z) - self.kcorr(z)

    def dVdz_per_sr(self, z):
        return self.cosmo.differential_comoving_volume(z).to(u.Mpc**3 / u.sr).value

    # -----------------------------------------------------------
    def predict_dNdz(self, z_array, Zlim, area_deg2):
        """dN/dz for all galaxies brighter than a single flux limit Zlim."""
        area_sr = area_deg2 * (np.pi / 180.0) ** 2
        dNdz = np.zeros_like(np.asarray(z_array, dtype=float))
        for i, z in enumerate(z_array):
            if z <= 0:
                continue
            Ml = np.clip(self.Mlim_of_z(z, Zlim), self.Mmin, self.Mmax)
            n_z = self.n_brighter_than(Ml, z)
            dV = self.dVdz_per_sr(z) * area_sr
            dNdz[i] = n_z * dV
        return dNdz

    def predict_dNdz_slice(self, z_array, mag_lo, mag_hi, area_deg2):
        """
        dN/dz for galaxies with apparent magnitude in [mag_lo, mag_hi):
        the difference of two cumulative flux-limited predictions
        (fainter limit minus brighter limit).
        """
        dNdz_hi = self.predict_dNdz(z_array, mag_hi, area_deg2)
        dNdz_lo = self.predict_dNdz(z_array, mag_lo, area_deg2)
        return np.clip(dNdz_hi - dNdz_lo, 0.0, None)

    # -----------------------------------------------------------
    def plot_flux_limited(self, z_grid, samples, filename="predicted_Nz.png", dpi=150):
        """
        samples: list of (Zlim, area_deg2, label) tuples, e.g.
        [(21.1, 1200.0, "WAVES-Wide"), (21.25, 65.0, "WAVES-Deep")]
        """
        fig, ax = plt.subplots(figsize=(7, 5))
        for Zlim, area, label in samples:
            dNdz = self.predict_dNdz(z_grid, Zlim, area)
            ax.plot(z_grid, dNdz, label=f"{label} (Z<{Zlim})")
        ax.set_xlabel("z")
        ax.set_ylabel("dN/dz")
        ax.legend()
        ax.set_title("Predicted N(z) from evolving Schechter LF")
        fig.tight_layout()
        fig.savefig(filename, dpi=dpi)
        print(f"Saved plot to {filename}")


# =====================================================================
# 2. Joint 3-parameter z_c(m) fitter (works on real OR model data)
# =====================================================================
class ZcJointFitter:
    """
    Fits z_c(m) = a * (m - m0)^p + c by matching the full dN/dz
    histogram shape in each magnitude slice simultaneously.

    Build with either:
      - ZcJointFitter(mag, z, ...)        real per-galaxy catalogue
      - ZcJointFitter.from_file(...)       catalogue loaded from disk
      - ZcJointFitter.from_model(model,...) synthetic data generated by
                                            a SchechterNzModel forward model
    """

    def __init__(
        self,
        mag,
        z,
        mag_edges=None,
        z_edges=None,
        m0=17.0,
        p0=(0.016, 1.5, 0.046),
        bounds=((1e-4, 0.2, 1e-4), (1.0, 5.0, 1.0)),
    ):
        self.mag = np.asarray(mag)
        self.z = np.asarray(z)
        self.mag_edges = np.asarray(mag_edges) if mag_edges is not None else np.arange(16, 23, 1)
        self.z_edges = np.asarray(z_edges) if z_edges is not None else np.arange(0.0, 1.001, 0.05)
        self.m0 = m0
        self.p0 = p0
        self.bounds = bounds

        self.mag_centres = self.mag_edges[:-1] + 0.5
        self.z_centres = 0.5 * (self.z_edges[:-1] + self.z_edges[1:])
        self.dz = np.diff(self.z_edges)
        self.z_grid = None
        self.valid_slices = None

        self.hist_list, self.err_list, self.n_gal_slice = [], [], []
        self.z_all = self.mag_all = self.density_all = self.err_all = None
        self.popt = self.pcov = None

        self.build_histograms()

    # -----------------------------------------------------------
    @classmethod
    def from_file(cls, filename, mag_col=0, z_col=1, **kwargs):
        """Load (mag, z) columns from a text catalogue."""
        mag = np.loadtxt(filename, usecols=mag_col)
        z = np.loadtxt(filename, usecols=z_col)
        return cls(mag, z, **kwargs)

    @classmethod
    def from_model(
        cls,
        model,
        mag_edges=None,
        z_grid=None,
        m0=17.0,
        p0=(0.016, 1.5, 0.046),
        bounds=((1e-4, 0.2, 1e-4), (1.0, 5.0, 1.0)),
    ):
        """
        Build a fitter directly from a SchechterNzModel's predicted
        SHAPE, not from any simulated or counted galaxies.

        For each magnitude slice, predict_dNdz_slice() is evaluated on
        a redshift grid and normalized to unit area (a probability
        density in z). These normalized curves -- one continuous
        function per slice -- are then fit jointly and UNWEIGHTED
        (every z point contributes equally) against the parametric
        z^2 * exp[-(z/z_c(m))^1.5] template, with z_c(m) = a(m-m0)^p+c
        shared across all slices. There's no notion of "how many
        galaxies" anywhere in this fit -- area_deg2 and survey size
        don't even enter, since normalizing to unit area removes them.
        """
        obj = cls.__new__(cls)  # bypass the raw-catalogue __init__
        obj.mag_edges = np.asarray(mag_edges) if mag_edges is not None else np.arange(16, 23, 1)
        obj.z_grid = np.asarray(z_grid) if z_grid is not None else np.linspace(1e-4, 1.0, 500)
        if obj.z_grid[-1] > model.zfit_max:
            print(f"NOTE: extrapolating the LF evolution (M*(z), phi*(z)) beyond its "
                  f"fitted range (z <= {model.zfit_max}) out to z = {obj.z_grid[-1]:.2f}.")
        obj.z_edges = obj.z_centres = obj.dz = None  # not used in shape mode
        obj.m0 = m0
        obj.p0 = p0
        obj.bounds = bounds
        obj.mag_centres = obj.mag_edges[:-1] + 0.5
        obj.mag = obj.z = None  # no raw catalogue backing this fitter

        shape_list, mag_bin_id, z_stack, valid_slices = [], [], [], []
        for mlo, mhi in zip(obj.mag_edges[:-1], obj.mag_edges[1:]):
            # area_deg2 cancels out entirely on normalization, so its
            # value is irrelevant -- use an arbitrary placeholder
            dNdz = model.predict_dNdz_slice(obj.z_grid, mlo, mhi, area_deg2=1.0)
            total = np.trapezoid(dNdz, obj.z_grid)
            if total <= 0:
                continue
            shape = dNdz / total   # normalized: integrates to 1 over z_grid

            shape_list.append(shape)
            mag_bin_id.append(np.full(len(obj.z_grid), mlo + 0.5))
            z_stack.append(obj.z_grid)
            valid_slices.append((mlo, mhi))

        obj.hist_list = shape_list          # reused by plot()
        obj.err_list = [None] * len(shape_list)
        obj.n_gal_slice = None              # meaningless in shape mode
        obj.valid_slices = valid_slices
        obj.z_all = np.concatenate(z_stack)
        obj.mag_all = np.concatenate(mag_bin_id)
        obj.density_all = np.concatenate(shape_list)
        obj.err_all = None                  # unweighted fit
        obj.popt = obj.pcov = None
        return obj

    # -----------------------------------------------------------
    def build_histograms(self):
        """Bin a raw catalogue into normalized dN/dz histograms per magnitude slice."""
        hist_list, err_list, mag_bin_id, z_stack, n_gal_slice = [], [], [], [], []

        for mlo, mhi in zip(self.mag_edges[:-1], self.mag_edges[1:]):
            mask = (self.mag >= mlo) & (self.mag < mhi)
            zi = self.z[mask]
            n_gal_slice.append(len(zi))

            counts, _ = np.histogram(zi, bins=self.z_edges)
            n_tot = counts.sum()
            if n_tot == 0:
                continue

            density = counts / (n_tot * self.dz)
            density_err = np.sqrt(np.maximum(counts, 1)) / (n_tot * self.dz)

            hist_list.append(density)
            err_list.append(density_err)
            mag_bin_id.append(np.full(len(self.z_centres), mlo + 0.5))
            z_stack.append(self.z_centres)

        self.hist_list = hist_list
        self.err_list = err_list
        self.n_gal_slice = n_gal_slice
        self.z_all = np.concatenate(z_stack)
        self.mag_all = np.concatenate(mag_bin_id)
        self.density_all = np.concatenate(hist_list)
        self.err_all = np.concatenate(err_list)

    # -----------------------------------------------------------
    def zc_of_m(self, m, a, p, c):
        """z_c(m) = a * (m - m0)^p + c, with (m - m0) clipped at zero below m0."""
        dm = np.clip(np.asarray(m, dtype=float) - self.m0, 0.0, None)
        return np.clip(a * dm**p + c, 1e-4, None)

    def _dNdz_shape(self, X, a, p, c):
        z_vals, m_vals = X
        zc = self.zc_of_m(m_vals, a, p, c)
        unnorm = z_vals**2 * np.exp(-(z_vals / zc) ** 1.5)

        z_max = self.z_edges[-1] if self.z_edges is not None else self.z_grid[-1]
        z_fine = np.linspace(1e-4, max(z_max * 2, 2.0), 2000)

        out = np.empty_like(unnorm)
        for m_unique in np.unique(m_vals):
            sel = m_vals == m_unique
            zc_i = self.zc_of_m(m_unique, a, p, c)
            shape_fine = z_fine**2 * np.exp(-(z_fine / zc_i) ** 1.5)
            norm = np.trapezoid(shape_fine, z_fine)
            out[sel] = unnorm[sel] / norm

        return out

    # -----------------------------------------------------------
    def fit(self):
        self.popt, self.pcov = curve_fit(
            self._dNdz_shape,
            (self.z_all, self.mag_all),
            self.density_all,
            sigma=self.err_all,           # None -> unweighted (shape mode)
            p0=self.p0,
            bounds=self.bounds,
            absolute_sigma=self.err_all is not None,
        )
        return self.popt, self.pcov

    @property
    def params(self):
        if self.popt is None:
            raise RuntimeError("Call .fit() first.")
        perr = np.sqrt(np.diag(self.pcov))
        return {
            "a": (self.popt[0], perr[0]),
            "p": (self.popt[1], perr[1]),
            "c": (self.popt[2], perr[2]),
        }

    def summary(self):
        print(f"Total stacked (mag, z) points used in fit: {len(self.z_all)}")

        shape_mode = self.n_gal_slice is None
        for idx, (mlo, mhi) in enumerate(
            self.valid_slices if shape_mode else zip(self.mag_edges[:-1], self.mag_edges[1:])
        ):
            # flag slices where the curve is still rising at the last
            # grid point -- the fitted template (which must peak+decline)
            # cannot represent such a distribution, and will distort z_c
            # for that slice (and, since a,p,c are shared, every slice)
            peak_at_edge = np.argmax(self.hist_list[idx]) >= len(self.hist_list[idx]) - 2
            flag = "  <-- WARNING: still rising at z_max, not turning over" if peak_at_edge else ""
            print(f"  slice {mlo:.0f}-{mhi:.0f}{flag}")

        p = self.params
        print("\nBest-fit joint parameters (shared across all magnitude slices):")
        print(f"  a = {p['a'][0]:.5f} +/- {p['a'][1]:.5f}")
        print(f"  p = {p['p'][0]:.5f} +/- {p['p'][1]:.5f}")
        print(f"  c = {p['c'][0]:.5f} +/- {p['c'][1]:.5f}")

        print(f"\nImplied z_c(m) and z_m(m) = 1.412 * z_c(m)  [m0 = {self.m0}]:")
        for mc in self.mag_centres:
            zc_m = self.zc_of_m(mc, *self.popt)
            print(f"  m={mc:.1f}: z_c={zc_m:.4f}, z_m={1.412*zc_m:.4f}")

    def plot(self, filename="zc_joint_fit.png", dpi=150):
        shape_mode = self.n_gal_slice is None
        slices = self.valid_slices if shape_mode else list(
            (mlo, mlo + 1) for mlo, n in zip(self.mag_edges[:-1], self.n_gal_slice) if n > 0
        )
        n_slices = len(slices)
        fig, axes = plt.subplots(1, n_slices, figsize=(3 * n_slices, 3), sharey=True)

        z_max = self.z_grid[-1] if shape_mode else self.z_edges[-1]
        z_fine = np.linspace(1e-4, z_max, 300)
        z_data = self.z_grid if shape_mode else self.z_centres

        for idx, (mlo, mhi) in enumerate(slices):
            ax = axes[idx] if n_slices > 1 else axes
            if shape_mode:
                ax.plot(z_data, self.hist_list[idx], "o", ms=2, label="model shape")
            else:
                ax.errorbar(z_data, self.hist_list[idx], yerr=self.err_list[idx], fmt="o", ms=3)
            model_curve = self._dNdz_shape((z_fine, np.full_like(z_fine, mlo + 0.5)), *self.popt)
            ax.plot(z_fine, model_curve, "-", label="fitted template")
            ax.set_title(f"{mlo:.0f}-{mhi:.0f}")
            ax.set_xlabel("z")

        (axes[0] if n_slices > 1 else axes).set_ylabel("dN/dz (normalized)")
        if n_slices > 0:
            (axes[0] if n_slices > 1 else axes).legend(fontsize=8)
        plt.tight_layout()
        plt.savefig(filename, dpi=dpi)
        print(f"\nSaved plot to {filename}")


# =====================================================================
# 3. Example usage
# =====================================================================
if __name__ == "__main__":
    model = SchechterNzModel()

    # sanity-check plot of the original cumulative flux-limited predictions
    z_grid = np.linspace(0.001, 0.5, 200)
    model.plot_flux_limited(
        z_grid,
        samples=[(21.1, 1200.0, "WAVES-Wide"), (21.25, 65.0, "WAVES-Deep")],
        filename="predicted_Nz.png",
    )

    # joint 3-parameter fit of z_c(m) to the model's own predicted
    # dN/dz SHAPE, sliced into apparent-magnitude bins. No counts, no
    # survey area/size, no Poisson weighting anywhere -- every z point
    # on every slice's normalized curve is weighted equally.
    #
    # z_grid here extends to z=1.0, past the LF fit's calibrated range
    # (zfit_max=0.5) -- M*(z) and phi*(z) are being extrapolated for
    # z>0.5. from_model() prints a note when this happens.
    fitter = ZcJointFitter.from_model(
        model,
        mag_edges=np.arange(16, 23, 1),
        z_grid=np.linspace(1e-4, 1.0, 500),
    )
    fitter.fit()
    fitter.summary()
    fitter.plot(filename="zc_joint_fit_from_model.png")


# ---------------------------------------------------------------
# Example usage
# ---------------------------------------------------------------
if __name__ == "__main__":
    fitter = ZcJointFitter.from_file("catalogue.txt")
    fitter.fit()
    fitter.summary()
    fitter.plot()